name: Build and Release

on:
  push:
    branches:
      - '*'  # This triggers the workflow on all pushes to all branches
jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'GUI/main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: haptic-cv-${{ github.run_number }}
          options: --onefile, --name "Haptic-CV", --windowed

  release:
    needs: pyinstaller-build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/haptic-cv-${{ github.run_number }}
          asset_name: haptic-cv-${{ github.run_number }}
          asset_content_type: application/octet-stream
